services:
  backup:
    build: .
    image: medzarka/homelab-rclone-sync:latest
    container_name: homelab_rclone_sync
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - CLOUD_REMOTE_NAME=${CLOUD_REMOTE_NAME}
      - CLOUD_DEST_PATH=${CLOUD_DEST_PATH}
      - RETENTION_WEEKS=${RETENTION_WEEKS}
      - BACKUP_CRON=${BACKUP_CRON}
      - HOSTNAME=${HOSTNAME}
      - CONTAINERS_TO_PAUSE=${CONTAINERS_TO_PAUSE}
      - SMTP_URL=${SMTP_URL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_TO=${SMTP_TO}
      - RCLONE_CONF_BASE64=${RCLONE_CONF_BASE64}
      - EXCLUDE_TXT_BASE64=${EXCLUDE_TXT_BASE64}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${BACKUP_SOURCE_DIR:-/home/mgrsys/DATA}:/data:ro
      - /etc/hostname:/etc/host_hostname:ro